build_debug:
  image: wutiarn/android
  stage: build
  script:
    - ./gradlew assembleDebug assembleCI
  artifacts:
    name: "edustor-android-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}"
    paths:
      - "app/build/outputs/"