build_debug:
  image: wutiarn/android
  stage: build
  script:
    - ./gradlew assembleDebug assembleCI
    - mv app/build/outputs/apk/* .
    - rm *-unaligned.apk
  artifacts:
    name: "edustor-android-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}"
    paths:
      - "*.apk"