build_CI:
  image: quay.io/wutiarn/android-base
  stage: build
  script:
    - ./gradlew assembleCI
    - mv app/build/outputs/apk/* .
    - rm -f *-unaligned.apk
  artifacts:
    name: "edustor-android-CI-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}"
    paths:
      - "*.apk"

build_release:
  image: quay.io/wutiarn/android-base
  stage: build
  script:
    - ./gradlew assembleRelease
    - mv app/build/outputs/apk/* .
    - rm -f *-unaligned.apk
  artifacts:
    name: "edustor-android-RELEASE-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}"
    paths:
      - "*.apk"
  only:
    - master

# REQUIRED ENVIRONMENTS
# EDUSTOR_ANDROID_CI_KEY_PASSWORD